---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: sample-user-scram
  labels:
    strimzi.io/cluster: event-bus
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
    # Consumer Groups
    - resource:
        type: group
        name: sample-group
        patternType: literal
      operation: Read
    - resource:
        type: group
        name: sample-consumer-reversed-group
        patternType: literal
      operation: Read
    # Consumer ACLs for topic apps.samples.greetings
    - resource:
        type: topic
        name: apps.samples.greetings
        patternType: literal
      operation: Read
    - resource:
        type: topic
        name: apps.samples.greetings
        patternType: literal
      operation: Describe
    - resource:
        type: topic
        name: apps.samples.greetings.reversed
        patternType: literal
      operation: Read
    - resource:
        type: topic
        name: apps.samples.greetings.reversed
        patternType: literal
      operation: Describe
    # Producer ACLs for topic apps.samples.greetings
    - resource:
        type: topic
        name: apps.samples.greetings
        patternType: literal
      operation: Write
    - resource:
        type: topic
        name: apps.samples.greetings
        patternType: literal
      operation: Create
    - resource:
        type: topic
        name: apps.samples.greetings
        patternType: literal
      operation: Describe
